/**
 * Copyright 2026 Stephen Thompson / The Founded Project
 *
 * Every sentence the Research Atlas says in its own voice lives here, so it
 * can be read and checked in one place (scripts/atlas/export_copy.py writes
 * this file out as Markdown for voice_check.py). Chapter theses, summaries,
 * claims, sources, and questions come from the manuscript files and are not
 * in this file.
 *
 * Voice rules that apply: website copy, so contractions are the default.
 * No em dashes. No reflexive contrast pivots. No shame language about
 * progress. "Stephen Thompson", never "Dr."
 */

export const COPY = {
  brand: {
    name: 'The Founded Project',
    sub: 'Research Atlas',
    edition: 'Private author edition',
  },

  nav: {
    start: 'Start here',
    study: 'Study',
    explore: 'Explore',
    evidence: 'Evidence',
    challenge: 'Challenge Room',
    mechanisms: 'Mechanisms',
    terms: 'Terms',
    revisit: 'Revisit',
    method: 'Method',
    gaps: 'Gaps',
  },

  start: {
    eyebrow: 'A Theory of Human Flourishing',
    title: 'Start here',
    lede: 'This is the private research companion to the manuscript. It collects the argument of every chapter, every claim with its sources, and the strongest objections, so you can find the best source for any claim in under a minute.',
    continueLabel: 'Continue where you stopped',
    continueNone: 'Your place isn\'t saved yet. Pick a door below.',
    doors: [
      { key: 'study', title: 'Study the argument', when: 'When you want to master a chapter. Five minutes, fifteen, or the whole thing, one card at a time.', href: '/atlas/study' },
      { key: 'explore', title: 'Find something', when: 'When you have a word in mind. Search every chapter, claim, source, and term, with forgiving spelling.', href: '/atlas/explore' },
      { key: 'evidence', title: 'Check the evidence', when: 'When someone challenges a claim. Each claim sits beside its sources, locators, and limits.', href: '/atlas/evidence' },
    ],
    secondary: [
      { title: 'Challenge Room', when: 'The strongest objections, and where each one stands.', href: '/atlas/challenge' },
      { title: 'Revisit queue', when: 'What you marked to come back to.', href: '/atlas/revisit' },
      { title: 'Method', when: 'How these records were built and what the labels mean.', href: '/atlas/method' },
    ],
    thesisLabel: 'The thesis',
    sequenceLabel: 'The sequence',
    recentLabel: 'Most recently revised chapters',
    pauseLine: 'You can stop anytime. Your place is saved on this device.',
  },

  study: {
    title: 'Study',
    lede: 'Six paths, one for each Part of the book. Pick a chapter, pick how long you have, and work one card at a time. Each card asks you to recall first, then shows the answer.',
    pathLabels: { five: '5 minutes', fifteen: '15 minutes', deep: 'Deep' },
    pathWhen: {
      five: 'The thesis and the shape of the chapter.',
      fifteen: 'Adds the key concepts, the main claims, and the sharpest objection.',
      deep: 'Every claim, source, objection, and study question in the chapter.',
    },
    reveal: 'Show the answer',
    hide: 'Hide',
    next: 'Next card',
    prev: 'Previous',
    finish: 'Finish',
    cardOf: (i, n) => `Card ${i} of ${n}`,
    markReviewed: 'Reviewed',
    markUncertain: 'Uncertain',
    markRevisit: 'Revisit',
    plainLanguage: 'Say it plainly',
    openClaim: 'Open the claim',
    openChapter: 'Open the chapter page',
    done: {
      title: 'That was the chapter.',
      body: 'Here\'s what you marked. These aren\'t scores. The uncertain and revisit cards are the useful ones; they tell you where to look next.',
      next: 'Next chapter',
      again: 'Go through it again',
      backToPaths: 'Back to the study paths',
    },
    prompts: {
      thesis: 'Say this chapter\'s argument in one sentence.',
      purpose: 'What job does this chapter do in the book?',
      readerProblem: 'What problem is the reader living with when they open this chapter?',
      movement: 'Walk the chapter\'s sections in order.',
      takeaway: 'What should a reader be able to do or see after this chapter?',
      concept: (name) => `Explain in your own words: ${name}`,
      claim: 'What is the evidence for this, and where does it sit in the draft?',
      challenge: 'What is the strongest objection to this chapter, and what is the answer?',
      firstSource: 'If someone challenged this chapter tonight, which source would you open first?',
      question: 'Take a minute with this one. It doesn\'t have an answer card.',
      architecture: 'How many sections does the draft have, and what are they?',
      related: 'Which chapters does this one lean on, and which lean on it?',
    },
    kinds: {
      thesis: 'Thesis', purpose: 'Purpose', readerProblem: 'Reader problem', movement: 'Movement', takeaway: 'Takeaway',
      concept: 'Key concept', claim: 'Claim', challenge: 'Challenge', firstSource: 'First source', question: 'Study question',
      workbook: 'Workbook question', architecture: 'Draft architecture', related: 'Related chapters', pullQuote: 'Pull quote',
    },
  },

  explore: {
    title: 'Explore',
    lede: 'Search every chapter, claim, source, challenge, and glossary term. Spelling doesn\'t have to be exact; close words and common synonyms match too.',
    placeholder: 'Search the atlas (press / anywhere)',
    kinds: { chapter: 'Chapter', claim: 'Claim', source: 'Source', challenge: 'Challenge', term: 'Term' },
    results: (n, q) => (n === 1 ? `1 result for “${q}”` : `${n} results for “${q}”`),
    none: 'No matches. Try a shorter word, or one of the terms below.',
    showMore: 'Show more',
    filtersLabel: 'Narrow it down',
    clear: 'Clear',
    expanded: 'Also matched:',
    startHints: 'Try a mechanism, an author, or a word from a chapter title.',
  },

  evidence: {
    title: 'Evidence',
    lede: 'Every claim in the ledger with its type, importance, and where its support stands. Open a claim to see it beside its sources.',
    counts: (n) => `${n} claims`,
    columns: { claim: 'Claim', chapter: 'Chapter', type: 'Type', importance: 'Importance', status: 'Support', sources: 'Sources' },
    statusHelp: {
      cited: 'A footnote sits on this sentence in the current draft.',
      mapped: 'The Research Map ties this claim to a source.',
      'mapped-cross-chapter': 'The source lives in another chapter\'s Research Map.',
      argued: 'The chapter\'s core claim. It rests on the sourced claims beneath it.',
      unsupported: 'No source found in the draft or the Research Map.',
    },
    typeHelp: {
      fact: 'An empirical claim about the world.',
      synthesis: 'The chapter\'s own integrative argument.',
      interpretation: 'A reading of evidence.',
      inference: 'A conclusion drawn beyond the evidence.',
      forecast: 'A claim about the future.',
      unverified: 'Not yet classified. Treat as open.',
    },
    importanceHelp: {
      'load-bearing': 'The chapter depends on it.',
      supporting: 'It supports the argument without being essential to it.',
      contextual: 'Background.',
      unverified: 'Not yet classified.',
    },
  },

  claim: {
    eyebrow: 'Claim',
    locationLabel: 'Where it sits',
    contextLabel: 'The paragraph around it',
    supportLabel: 'Supporting sources',
    qualifyingLabel: 'Qualifying sources',
    competingLabel: 'Strongest competing explanation',
    establishesLabel: 'What the evidence establishes',
    notEstablishesLabel: 'What it does not establish',
    challengesLabel: 'Challenge records',
    relatedLabel: 'Related claims',
    noSources: 'No source is attached to this claim yet. That\'s a gap, and it\'s listed on the Gaps page.',
    noCompeting: 'No competing explanation has been mapped to this specific claim yet. The chapter-level counterpoints are listed under Challenge records.',
    notRecorded: 'Not recorded yet.',
    export: 'Export claim packet',
    copy: 'Copy packet',
    copied: 'Packet copied.',
    exported: 'Packet downloaded.',
    unreviewedNote: 'Type and importance were assigned by rule from the manuscript files and haven\'t been reviewed by a person yet.',
    classificationBasis: 'basis',
  },

  source: {
    eyebrow: 'Source',
    citationLabel: 'Citation',
    linksLabel: 'Links',
    useLabel: 'What the Research Map says it validates',
    notesLabel: 'Notes from the footnote',
    claimsLabel: 'Claims it supports',
    qualifiesLabel: 'Claims it qualifies',
    challengesLabel: 'Challenges that mention it',
    appearancesLabel: 'Where it appears',
    pointsTo: 'This entry points to a fuller record:',
    duplicates: 'Possibly the same work as',
    linkStates: { reachable: 'reachable', blocked: 'blocked to automated checks (open by hand)', error: 'broken', unreachable: 'unreachable' },
    noLinks: 'No URL on file. Open the work from the citation.',
  },

  challenge: {
    title: 'Challenge Room',
    lede: 'The strongest objections to each chapter, taken from the Research Maps and the Contrarian Reviews, with where each one stands. Use the checklist when a claim is under pressure.',
    filters: { chapter: 'Chapter', origin: 'Origin', resolution: 'Status', topic: 'Topic' },
    origins: { 'research-map': 'Research Map counterpoint', 'contrarian-review': 'Contrarian Review flag' },
    resolutions: {
      open: 'Open', 'revision-suggested': 'Revision suggested', 'no-change-needed': 'No change needed',
      'needs-stephen': 'Needs your decision', watch: 'Watch',
    },
    topics: { evidence: 'Evidence', 'model-fidelity': 'Model fidelity', craft: 'Craft and voice' },
    fields: { proposition: 'Proposition', objection: 'Objection', evidence: 'Evidence for the objection', response: 'Response', revision: 'Revision', remaining: 'Remaining uncertainty', claims: 'Claims it touches' },
    checklistTitle: 'When a claim is challenged',
    checklist: [
      'Which sentence is contested, and is it a fact, a synthesis, an interpretation, an inference, or a forecast?',
      'Does the cited source establish the whole sentence, or only part of it?',
      'What is the strongest competing explanation, and does the chapter answer it?',
      'Does the claim increase agency, improve governance, strengthen discernment, or support contribution? If it does none of these, why is it in the book?',
      'Does the claim stay inside the Moral Boundary Principle, or does it treat a violation as a force to balance?',
      'What evidence would narrow or overturn the claim?',
      'Is a page, section, or link still missing?',
    ],
    counts: (n) => `${n} records`,
  },

  mechanisms: {
    title: 'Mechanisms',
    lede: 'The recurring mechanisms the book uses, grouped the way the book groups them: agency\'s five parts, the three forces that erode it, the Dynamic Balance tensions, and the stage-specific structures. Each one lists the chapters and claims that use it.',
    chapters: 'Chapters',
    claims: 'Claims',
    terms: 'Glossary terms',
    basis: 'Tagged from',
  },

  terms: {
    title: 'Terms',
    lede: 'The working vocabulary from the Founded Glossary. Each term has a working definition, what it isn\'t, and a plain-language version.',
    filter: 'Filter terms',
    plain: 'Plain language',
    notLabel: 'What it is not',
    whereLabel: 'Where it appears in the model',
    chaptersLabel: 'Chapters that use it',
  },

  revisit: {
    title: 'Revisit',
    lede: 'What you marked to come back to, your bookmarks, and your notes. All of it lives on this device.',
    queue: 'Revisit queue',
    bookmarks: 'Bookmarks',
    notes: 'Notes',
    marks: 'Marks',
    empty: 'This list is empty so far.',
    remove: 'Remove',
    clear: 'Clear everything saved on this device',
    clearConfirm: 'This removes your progress, marks, bookmarks, and notes from this browser. Continue?',
    progressTitle: 'Study progress',
  },

  gaps: {
    title: 'Gaps',
    lede: 'The evidentiary gaps the extractor found, in priority order. P1 first. Every line points to a record you can open.',
    regenerate: 'Regenerate by running scripts/atlas/build_atlas.py after editing the manuscript.',
    downloads: 'Downloads',
  },

  settings: {
    title: 'Reading settings',
    type: 'Type size',
    typeOptions: ['Default', 'Larger', 'Largest'],
    width: 'Line width',
    widthOptions: { narrow: 'Narrow', medium: 'Medium', wide: 'Wide' },
    contrast: 'Contrast',
    contrastOptions: { default: 'Bone', high: 'High', dark: 'Night' },
    motion: 'Motion',
    motionOptions: { default: 'Default', reduced: 'Reduced' },
    focus: 'Focus mode',
    focusHelp: 'Hides the navigation and side panels. Press F to toggle.',
    guide: 'Reading guide',
    guideHelp: 'A band that marks the line you are on.',
    close: 'Done',
    shortcutsTitle: 'Keyboard',
    shortcuts: [
      ['/', 'Search'],
      ['F', 'Focus mode'],
      ['?', 'This panel'],
      ['← →', 'Previous and next card'],
      ['Space', 'Show the answer'],
      ['R U V', 'Mark reviewed, uncertain, revisit'],
      ['Esc', 'Close'],
    ],
  },

  common: {
    chapter: 'Chapter',
    part: 'Part',
    stage: 'Stage',
    draft: 'Draft',
    words: 'words',
    claims: 'claims',
    sources: 'sources',
    challenges: 'challenges',
    open: 'Open',
    back: 'Back',
    bookmark: 'Bookmark',
    bookmarked: 'Bookmarked',
    addRevisit: 'Add to revisit',
    inRevisit: 'In revisit queue',
    noteLabel: 'Private note',
    notePlaceholder: 'Anything you want to remember about this. Stays on this device.',
    saved: 'Saved.',
    unreviewed: 'unreviewed',
    authorOnly: 'Author-private material. Keep out of any public edition.',
    sourceOfText: 'From',
  },

  chapter: {
    tabs: { overview: 'Overview', claims: 'Claims', sources: 'Sources', challenge: 'Challenge', study: 'Study prompts' },
    thesis: 'Thesis',
    fiveMinute: 'Five-minute summary',
    purpose: 'Purpose',
    readerProblem: 'Reader problem',
    movement: 'Movement',
    takeaway: 'Takeaway',
    keyConcepts: 'Key concepts',
    mechanisms: 'Mechanisms',
    architecture: 'Draft architecture',
    related: 'Related chapters',
    coreTheory: 'Core theory files',
    pullQuotes: 'Pull quotes',
    pullQuoteState: { yes: 'in the current draft', partial: 'partly in the current draft', no: 'not in the current draft' },
    research: 'Research pass',
    review: 'Contrarian Review checklist',
    revisions: 'Top revisions to consider',
    openIssues: 'Open issues',
    diagnostic: 'Diagnostic questions',
    workbook: 'Workbook questions',
    inquiry: 'Inquiry questions for the drafting agent',
    studyThis: 'Study this chapter',
    markReviewed: 'Mark chapter reviewed',
  },
}

export const STATUS_LABEL = {
  cited: 'Cited in draft',
  mapped: 'Mapped in Research Map',
  'mapped-cross-chapter': 'Mapped, source in another chapter',
  argued: 'Argued (core claim)',
  unsupported: 'Unsupported',
}

export const ROLE_LABEL = {
  direct: 'Direct',
  corroborating: 'Corroborating',
  adversarial: 'Adversarial',
  contextual: 'Pointer',
}
